language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
#  - "dev"

matrix:
  include:
    - perl: "5.22-thr"
      env:
        - CHECKBASHISMS=1
        - DIST=trusty
      dist: trusty
      sudo: required
      before_install:
        - dpkg -l rsync make
        - sudo apt-get update
        - sudo apt-get install -y --no-install-recommends devscripts
        - eval $(curl https://travis-perl.github.io/init)
        - build-perl
        - perl -V
      script:
        - make test
    - perl: "5.20-thr"
      env: DIST=precise
      dist: precise
    - perl: "5.10-thr"
      env: DIST=trusty
      dist: trusty

sudo: false
before_install:
   - eval $(curl https://travis-perl.github.io/init)
   - build-perl
   - perl -V

install:
   - yes '' | cpanm --verbose --notest --skip-satisfied Config::File File::BaseDir File::Rsync File::Touch File::Which Moo Test::Differences Test::File Devel::Cover::Report::Coveralls String::Random String::Expand File::Slurper
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 PATH=${PERLBREW_PATH}:${PATH}

script:
   - make pureperltest

after_success:
   - make coveralls


notifications:
  irc: "irc.lugs.ch#kivamon"
