site_name: Unburden Your Home Directory
pages:
  - Project Home: index.md
  - Installation and Dependencies: installation.md
  - Getting Started: howto.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md
  - Source Code: source-code.md
  - License, Copyright and Author: license.md
  - Contact and Community: contact.md
  - Plans, Known Issues, TODO: todo.md
  - Bugs: bugs.md
  - Quality Assurance: qa.md
  - See Also: see-also.md
  - "Appendix: Manual page unburden-home-dir(1)": unburden-home-dir.1.md
  - "Appendix: Retriving PGP Keys Used In The Project": pgp.md
theme: readthedocs
repo_url: https://github.com/xtaran/unburden-home-dir
site_author: Axel Beckert
use_directory_urls: false
markdown_extensions:
  - smarty
  - footnotes
site_dir: html
